# Generated by Django 3.2.8 on 2023-10-09 08:31

import apps.common.fileUpload.userPath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0002_auto_20231004_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_banner_image',
            field=models.ImageField(null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Default Banner Resmi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_profile_image',
            field=models.ImageField(null=True, upload_to=apps.common.fileUpload.userPath.userDirectoryPath, verbose_name='Default Profil Resmi'),
        ),
    ]
