# Generated by Django 3.2.22 on 2023-10-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_educationquestionsanswers_educationquestionsanswerstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationquestionsanswers',
            old_name='answers',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='educationquestionsanswers',
            old_name='questions',
            new_name='question',
        ),
    ]
